/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppRecordingsRouteImport } from './routes/app.recordings'
import { Route as AppRecordRouteImport } from './routes/app.record'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppFieldRouteImport } from './routes/app.field'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as ApiPublicSeedRouteImport } from './routes/api/public/seed'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordingsRoute = AppRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordRoute = AppRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSeedRoute = ApiPublicSeedRouteImport.update({
  id: '/api/public/seed',
  path: '/api/public/seed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/field': typeof AppFieldRoute
  '/app/history': typeof AppHistoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/record': typeof AppRecordRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/report': typeof AppReportRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/team': typeof AppTeamRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/field': typeof AppFieldRoute
  '/app/history': typeof AppHistoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/record': typeof AppRecordRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/report': typeof AppReportRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/team': typeof AppTeamRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/field': typeof AppFieldRoute
  '/app/history': typeof AppHistoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/record': typeof AppRecordRoute
  '/app/recordings': typeof AppRecordingsRoute
  '/app/report': typeof AppReportRoute
  '/app/reports': typeof AppReportsRoute
  '/app/review': typeof AppReviewRoute
  '/app/team': typeof AppTeamRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/api/public/seed': typeof ApiPublicSeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/field'
    | '/app/history'
    | '/app/messages'
    | '/app/queue'
    | '/app/record'
    | '/app/recordings'
    | '/app/report'
    | '/app/reports'
    | '/app/review'
    | '/app/team'
    | '/app/workspace'
    | '/api/public/seed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/field'
    | '/app/history'
    | '/app/messages'
    | '/app/queue'
    | '/app/record'
    | '/app/recordings'
    | '/app/report'
    | '/app/reports'
    | '/app/review'
    | '/app/team'
    | '/app/workspace'
    | '/api/public/seed'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/dashboard'
    | '/app/field'
    | '/app/history'
    | '/app/messages'
    | '/app/queue'
    | '/app/record'
    | '/app/recordings'
    | '/app/report'
    | '/app/reports'
    | '/app/review'
    | '/app/team'
    | '/app/workspace'
    | '/api/public/seed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedRoute: typeof ApiPublicSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recordings': {
      id: '/app/recordings'
      path: '/recordings'
      fullPath: '/app/recordings'
      preLoaderRoute: typeof AppRecordingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/record': {
      id: '/app/record'
      path: '/record'
      fullPath: '/app/record'
      preLoaderRoute: typeof AppRecordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/field': {
      id: '/app/field'
      path: '/field'
      fullPath: '/app/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/seed': {
      id: '/api/public/seed'
      path: '/api/public/seed'
      fullPath: '/api/public/seed'
      preLoaderRoute: typeof ApiPublicSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFieldRoute: typeof AppFieldRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRecordRoute: typeof AppRecordRoute
  AppRecordingsRoute: typeof AppRecordingsRoute
  AppReportRoute: typeof AppReportRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFieldRoute: AppFieldRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppQueueRoute: AppQueueRoute,
  AppRecordRoute: AppRecordRoute,
  AppRecordingsRoute: AppRecordingsRoute,
  AppReportRoute: AppReportRoute,
  AppReportsRoute: AppReportsRoute,
  AppReviewRoute: AppReviewRoute,
  AppTeamRoute: AppTeamRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedRoute: ApiPublicSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
